version: 2.1

defaults: &defaults
  working_directory: ~/repo
  environment:
    LEIN_ROOT: "true"
    JVM_OPTS: -Xmx3200m

jobs:
  checkout_code:
    docker:
      - image: circleci/clojure:lein-2.9.0
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "project.clj" }}
            - v2-dependencies-
      - run:
          name: Downloading deps
          command: |
            lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v2-dependencies-{{ checksum "project.clj" }}
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - .m2
            - repo

  lint_code:
    docker:
      - image: circleci/clojure:lein-2.9.0
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Install make
          command: |
            sudo apt-get install make
      - run:
          name: Running Eastwood
          command: |
            make eastwood
      - run:
          name: Running cljfmt
          command: |
            make cljfmt

  test_code:
    description: Run tests
    parameters:
      jdk-version:
        description: Version of JDK to test against
        type: string
        default: ""
    docker:
      - image: circleci/clojure:<< parameters.jdk-version >>lein-2.9.0
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Install make
          command: |
            sudo apt-get install make
      - run:
          name: Running Clojure 1.8 tests
          environment:
            VERSION: "1.8"
          command: make test
      - run:
          name: Running Clojure 1.9 tests
          environment:
            VERSION: "1.9"
          command: make test
      - run:
          name: Running Clojure 1.10 tests
          environment:
            VERSION: "1.10"
          command: make test
      - run:
          name: Running Clojure master tests
          environment:
            VERSION: "master"
          command: make test


workflows:
  version: 2.1
  build_and_test:
    jobs:
      - checkout_code
      - lint_code:
          name: Code Linting
          requires:
            - checkout_code
      - test_code:
          name: Oracale (?) JDK 8 tests
          requires:
            - checkout_code
      - test_code:
          name: Open JDK 8 tests
          jdk-version: openjdk-8-
          requires:
            - checkout_code
      - test_code:
          name : Open JDK 11 tests
          jdk-version: openjdk-11-
          requires:
            - checkout_code
